app:
  name: test
  version: v0.0.1
logger:
  level: debug
  encoding: console #console or json
http:
  enabled: true
  port: 8080
db:
  enabled: true
  type: postgres
  schema: test
  showsql: true
  connectionstring: "host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai"
security:
  enabled: true
  clientid: aruna
  clientsecret: bfd43856-1320-4703-b029-951abb60dbba
  tokenuri: https://sso-plataformagt.gtconsultoria.com.br/auth/realms/plataformagt/protocol/openid-connect/token
  jwkuri: https://sso-plataformagt.gtconsultoria.com.br/auth/realms/plataformagt/protocol/openid-connect/certs