app:
  name: test
  version: v0.0.1
logger:
  level: debug
  encoding: console #console or json
http:
  enabled: true
  port: 8080
db:
  enabled: true
  type: postgres
  showsql: true
  connectionstring: "host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai"